<p>Fout tijdens de handmatige import van <a href="/instances/{{$instance_id}}"><strong>{{ $instance_name }}</strong></a> instance. 
    Bericht: {{ $exception_message }}</p>