<p>Errore durante il ripristino <strong>{{ $backup_name }}</strong> backup. Message: {{ $exception_message }}</p>
