<p>Erro durante a exclus√£o <strong>{{ $backup_name }}</strong> backup. Message: {{ $exception_message }}</p>
